name: Nodejs-demo-app CI/CD

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master" 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f Docker/Dockerfile -t helion444/nodejs-demo-app:alpine3.22 -t helion444/nodejs-demo-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push helion444/nodejs-demo-app:alpine3.22
          docker push helion444/nodejs-demo-app:${{ github.sha }}

      - name: Clean up Docker images
        run: docker image prune -f
